# Generated by Django 5.1.1 on 2024-09-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epi_shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome_de_usuario', models.CharField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('tipo_de_usuario', models.CharField(choices=[('Cliente', 'Cliente'), ('Funcionario', 'Funcionário'), ('Gerente', 'Gerente')], max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
